language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules

env:
  - "PUBLIC_URL=/eatsheet"

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master
